-- WeddingMall.Online — all-India locations seed.
--
-- Generated from src/data/india-locations.ts. The app already unions this list
-- in at runtime, so it works without this file; run this only when you want the
-- WEBSITE's own selectors (which read `locations` directly) to see the same list.
--
-- Safe to re-run: it never touches or renames a row you already have — it only
-- inserts cities that are missing.

insert into public.locations (state, city)
select v.state, v.city
from (values
  ('Andaman and Nicobar Islands', 'Port Blair'),
  ('Andaman and Nicobar Islands', 'Swaraj Dweep'),
  ('Andaman and Nicobar Islands', 'Shaheed Dweep'),
  ('Andaman and Nicobar Islands', 'Diglipur'),
  ('Andaman and Nicobar Islands', 'Mayabunder'),
  ('Andaman and Nicobar Islands', 'Rangat'),
  ('Andaman and Nicobar Islands', 'Car Nicobar'),
  ('Andaman and Nicobar Islands', 'Campbell Bay'),
  ('Andhra Pradesh', 'Visakhapatnam'),
  ('Andhra Pradesh', 'Vijayawada'),
  ('Andhra Pradesh', 'Guntur'),
  ('Andhra Pradesh', 'Nellore'),
  ('Andhra Pradesh', 'Kurnool'),
  ('Andhra Pradesh', 'Rajahmundry'),
  ('Andhra Pradesh', 'Kakinada'),
  ('Andhra Pradesh', 'Tirupati'),
  ('Andhra Pradesh', 'Anantapur'),
  ('Andhra Pradesh', 'Kadapa'),
  ('Andhra Pradesh', 'Vizianagaram'),
  ('Andhra Pradesh', 'Eluru'),
  ('Andhra Pradesh', 'Ongole'),
  ('Andhra Pradesh', 'Nandyal'),
  ('Andhra Pradesh', 'Amaravati'),
  ('Andhra Pradesh', 'Machilipatnam'),
  ('Andhra Pradesh', 'Adoni'),
  ('Andhra Pradesh', 'Tenali'),
  ('Andhra Pradesh', 'Proddatur'),
  ('Andhra Pradesh', 'Chittoor'),
  ('Andhra Pradesh', 'Hindupur'),
  ('Andhra Pradesh', 'Srikakulam'),
  ('Andhra Pradesh', 'Bhimavaram'),
  ('Andhra Pradesh', 'Madanapalle'),
  ('Andhra Pradesh', 'Guntakal'),
  ('Andhra Pradesh', 'Dharmavaram'),
  ('Andhra Pradesh', 'Gudivada'),
  ('Andhra Pradesh', 'Narasaraopet'),
  ('Andhra Pradesh', 'Tadepalligudem'),
  ('Andhra Pradesh', 'Srikalahasti'),
  ('Arunachal Pradesh', 'Itanagar'),
  ('Arunachal Pradesh', 'Naharlagun'),
  ('Arunachal Pradesh', 'Pasighat'),
  ('Arunachal Pradesh', 'Tawang'),
  ('Arunachal Pradesh', 'Ziro'),
  ('Arunachal Pradesh', 'Bomdila'),
  ('Arunachal Pradesh', 'Aalo'),
  ('Arunachal Pradesh', 'Tezu'),
  ('Arunachal Pradesh', 'Roing'),
  ('Arunachal Pradesh', 'Namsai'),
  ('Arunachal Pradesh', 'Changlang'),
  ('Arunachal Pradesh', 'Khonsa'),
  ('Arunachal Pradesh', 'Daporijo'),
  ('Arunachal Pradesh', 'Seppa'),
  ('Arunachal Pradesh', 'Yingkiong'),
  ('Assam', 'Guwahati'),
  ('Assam', 'Silchar'),
  ('Assam', 'Dibrugarh'),
  ('Assam', 'Jorhat'),
  ('Assam', 'Nagaon'),
  ('Assam', 'Tinsukia'),
  ('Assam', 'Tezpur'),
  ('Assam', 'Bongaigaon'),
  ('Assam', 'Dhubri'),
  ('Assam', 'Diphu'),
  ('Assam', 'Golaghat'),
  ('Assam', 'Sivasagar'),
  ('Assam', 'Karimganj'),
  ('Assam', 'Goalpara'),
  ('Assam', 'Barpeta'),
  ('Assam', 'North Lakhimpur'),
  ('Assam', 'Mangaldoi'),
  ('Assam', 'Hailakandi'),
  ('Assam', 'Nalbari'),
  ('Assam', 'Haflong'),
  ('Assam', 'Kokrajhar'),
  ('Assam', 'Duliajan'),
  ('Bihar', 'Patna'),
  ('Bihar', 'Gaya'),
  ('Bihar', 'Bhagalpur'),
  ('Bihar', 'Muzaffarpur'),
  ('Bihar', 'Darbhanga'),
  ('Bihar', 'Purnia'),
  ('Bihar', 'Ara'),
  ('Bihar', 'Begusarai'),
  ('Bihar', 'Katihar'),
  ('Bihar', 'Munger'),
  ('Bihar', 'Chapra'),
  ('Bihar', 'Danapur'),
  ('Bihar', 'Bettiah'),
  ('Bihar', 'Saharsa'),
  ('Bihar', 'Sasaram'),
  ('Bihar', 'Hajipur'),
  ('Bihar', 'Dehri'),
  ('Bihar', 'Siwan'),
  ('Bihar', 'Motihari'),
  ('Bihar', 'Nawada'),
  ('Bihar', 'Bagaha'),
  ('Bihar', 'Buxar'),
  ('Bihar', 'Kishanganj'),
  ('Bihar', 'Sitamarhi'),
  ('Bihar', 'Jamalpur'),
  ('Bihar', 'Jehanabad'),
  ('Bihar', 'Aurangabad'),
  ('Bihar', 'Lakhisarai'),
  ('Bihar', 'Madhubani'),
  ('Bihar', 'Samastipur'),
  ('Bihar', 'Supaul'),
  ('Bihar', 'Araria'),
  ('Bihar', 'Banka'),
  ('Bihar', 'Bhabua'),
  ('Bihar', 'Gopalganj'),
  ('Bihar', 'Khagaria'),
  ('Bihar', 'Madhepura'),
  ('Bihar', 'Bihar Sharif'),
  ('Bihar', 'Sheikhpura'),
  ('Bihar', 'Sheohar'),
  ('Bihar', 'Arwal'),
  ('Bihar', 'Jamui'),
  ('Bihar', 'Bihta'),
  ('Bihar', 'Sonpur'),
  ('Bihar', 'Barh'),
  ('Bihar', 'Masaurhi'),
  ('Bihar', 'Rajgir'),
  ('Bihar', 'Nalanda'),
  ('Bihar', 'Forbesganj'),
  ('Bihar', 'Mokama'),
  ('Chandigarh', 'Chandigarh'),
  ('Chandigarh', 'Manimajra'),
  ('Chhattisgarh', 'Raipur'),
  ('Chhattisgarh', 'Bhilai'),
  ('Chhattisgarh', 'Bilaspur'),
  ('Chhattisgarh', 'Korba'),
  ('Chhattisgarh', 'Durg'),
  ('Chhattisgarh', 'Rajnandgaon'),
  ('Chhattisgarh', 'Raigarh'),
  ('Chhattisgarh', 'Jagdalpur'),
  ('Chhattisgarh', 'Ambikapur'),
  ('Chhattisgarh', 'Dhamtari'),
  ('Chhattisgarh', 'Mahasamund'),
  ('Chhattisgarh', 'Chirmiri'),
  ('Chhattisgarh', 'Janjgir'),
  ('Chhattisgarh', 'Kanker'),
  ('Chhattisgarh', 'Kawardha'),
  ('Chhattisgarh', 'Bemetara'),
  ('Chhattisgarh', 'Balod'),
  ('Chhattisgarh', 'Baikunthpur'),
  ('Chhattisgarh', 'Sukma'),
  ('Chhattisgarh', 'Dantewada'),
  ('Chhattisgarh', 'Naya Raipur'),
  ('Dadra and Nagar Haveli and Daman and Diu', 'Silvassa'),
  ('Dadra and Nagar Haveli and Daman and Diu', 'Daman'),
  ('Dadra and Nagar Haveli and Daman and Diu', 'Diu'),
  ('Dadra and Nagar Haveli and Daman and Diu', 'Moti Daman'),
  ('Dadra and Nagar Haveli and Daman and Diu', 'Nani Daman'),
  ('Delhi', 'New Delhi'),
  ('Delhi', 'Dwarka'),
  ('Delhi', 'Rohini'),
  ('Delhi', 'Saket'),
  ('Delhi', 'Karol Bagh'),
  ('Delhi', 'Pitampura'),
  ('Delhi', 'Janakpuri'),
  ('Delhi', 'Vasant Kunj'),
  ('Delhi', 'Chattarpur'),
  ('Delhi', 'Mayur Vihar'),
  ('Delhi', 'Rajouri Garden'),
  ('Delhi', 'Paschim Vihar'),
  ('Delhi', 'Shahdara'),
  ('Delhi', 'Najafgarh'),
  ('Delhi', 'Narela'),
  ('Delhi', 'Connaught Place'),
  ('Goa', 'Panaji'),
  ('Goa', 'Margao'),
  ('Goa', 'Vasco da Gama'),
  ('Goa', 'Mapusa'),
  ('Goa', 'Ponda'),
  ('Goa', 'Bicholim'),
  ('Goa', 'Curchorem'),
  ('Goa', 'Canacona'),
  ('Goa', 'Calangute'),
  ('Goa', 'Candolim'),
  ('Goa', 'Anjuna'),
  ('Goa', 'Porvorim'),
  ('Goa', 'Old Goa'),
  ('Goa', 'Quepem'),
  ('Goa', 'Sanquelim'),
  ('Goa', 'Valpoi'),
  ('Gujarat', 'Ahmedabad'),
  ('Gujarat', 'Surat'),
  ('Gujarat', 'Vadodara'),
  ('Gujarat', 'Rajkot'),
  ('Gujarat', 'Bhavnagar'),
  ('Gujarat', 'Jamnagar'),
  ('Gujarat', 'Gandhinagar'),
  ('Gujarat', 'Junagadh'),
  ('Gujarat', 'Anand'),
  ('Gujarat', 'Nadiad'),
  ('Gujarat', 'Navsari'),
  ('Gujarat', 'Bharuch'),
  ('Gujarat', 'Mehsana'),
  ('Gujarat', 'Morbi'),
  ('Gujarat', 'Surendranagar'),
  ('Gujarat', 'Bhuj'),
  ('Gujarat', 'Gandhidham'),
  ('Gujarat', 'Vapi'),
  ('Gujarat', 'Valsad'),
  ('Gujarat', 'Palanpur'),
  ('Gujarat', 'Porbandar'),
  ('Gujarat', 'Veraval'),
  ('Gujarat', 'Godhra'),
  ('Gujarat', 'Patan'),
  ('Gujarat', 'Dahod'),
  ('Gujarat', 'Amreli'),
  ('Gujarat', 'Botad'),
  ('Gujarat', 'Jetpur'),
  ('Gujarat', 'Himatnagar'),
  ('Gujarat', 'Modasa'),
  ('Gujarat', 'Deesa'),
  ('Gujarat', 'Ankleshwar'),
  ('Gujarat', 'Kalol'),
  ('Gujarat', 'Dwarka'),
  ('Gujarat', 'Somnath'),
  ('Gujarat', 'Mandvi'),
  ('Gujarat', 'Statue of Unity'),
  ('Haryana', 'Gurugram'),
  ('Haryana', 'Faridabad'),
  ('Haryana', 'Panipat'),
  ('Haryana', 'Ambala'),
  ('Haryana', 'Yamunanagar'),
  ('Haryana', 'Rohtak'),
  ('Haryana', 'Hisar'),
  ('Haryana', 'Karnal'),
  ('Haryana', 'Sonipat'),
  ('Haryana', 'Panchkula'),
  ('Haryana', 'Bhiwani'),
  ('Haryana', 'Sirsa'),
  ('Haryana', 'Bahadurgarh'),
  ('Haryana', 'Jind'),
  ('Haryana', 'Kurukshetra'),
  ('Haryana', 'Kaithal'),
  ('Haryana', 'Rewari'),
  ('Haryana', 'Palwal'),
  ('Haryana', 'Narnaul'),
  ('Haryana', 'Fatehabad'),
  ('Haryana', 'Gohana'),
  ('Haryana', 'Tohana'),
  ('Haryana', 'Hansi'),
  ('Haryana', 'Jhajjar'),
  ('Haryana', 'Charkhi Dadri'),
  ('Haryana', 'Nuh'),
  ('Haryana', 'Pinjore'),
  ('Haryana', 'Kalka'),
  ('Haryana', 'Manesar'),
  ('Himachal Pradesh', 'Shimla'),
  ('Himachal Pradesh', 'Solan'),
  ('Himachal Pradesh', 'Dharamshala'),
  ('Himachal Pradesh', 'Mandi'),
  ('Himachal Pradesh', 'Palampur'),
  ('Himachal Pradesh', 'Baddi'),
  ('Himachal Pradesh', 'Nahan'),
  ('Himachal Pradesh', 'Paonta Sahib'),
  ('Himachal Pradesh', 'Sundernagar'),
  ('Himachal Pradesh', 'Chamba'),
  ('Himachal Pradesh', 'Una'),
  ('Himachal Pradesh', 'Hamirpur'),
  ('Himachal Pradesh', 'Bilaspur'),
  ('Himachal Pradesh', 'Kullu'),
  ('Himachal Pradesh', 'Manali'),
  ('Himachal Pradesh', 'Kangra'),
  ('Himachal Pradesh', 'Nurpur'),
  ('Himachal Pradesh', 'Dalhousie'),
  ('Himachal Pradesh', 'Kasauli'),
  ('Himachal Pradesh', 'Keylong'),
  ('Himachal Pradesh', 'Reckong Peo'),
  ('Himachal Pradesh', 'Nalagarh'),
  ('Himachal Pradesh', 'McLeod Ganj'),
  ('Jammu and Kashmir', 'Srinagar'),
  ('Jammu and Kashmir', 'Jammu'),
  ('Jammu and Kashmir', 'Anantnag'),
  ('Jammu and Kashmir', 'Baramulla'),
  ('Jammu and Kashmir', 'Udhampur'),
  ('Jammu and Kashmir', 'Kathua'),
  ('Jammu and Kashmir', 'Sopore'),
  ('Jammu and Kashmir', 'Rajouri'),
  ('Jammu and Kashmir', 'Poonch'),
  ('Jammu and Kashmir', 'Kupwara'),
  ('Jammu and Kashmir', 'Pulwama'),
  ('Jammu and Kashmir', 'Budgam'),
  ('Jammu and Kashmir', 'Ganderbal'),
  ('Jammu and Kashmir', 'Bandipora'),
  ('Jammu and Kashmir', 'Kulgam'),
  ('Jammu and Kashmir', 'Shopian'),
  ('Jammu and Kashmir', 'Doda'),
  ('Jammu and Kashmir', 'Kishtwar'),
  ('Jammu and Kashmir', 'Ramban'),
  ('Jammu and Kashmir', 'Reasi'),
  ('Jammu and Kashmir', 'Samba'),
  ('Jammu and Kashmir', 'Gulmarg'),
  ('Jammu and Kashmir', 'Pahalgam'),
  ('Jammu and Kashmir', 'Sonamarg'),
  ('Jammu and Kashmir', 'Katra'),
  ('Jharkhand', 'Ranchi'),
  ('Jharkhand', 'Jamshedpur'),
  ('Jharkhand', 'Dhanbad'),
  ('Jharkhand', 'Bokaro Steel City'),
  ('Jharkhand', 'Deoghar'),
  ('Jharkhand', 'Hazaribagh'),
  ('Jharkhand', 'Giridih'),
  ('Jharkhand', 'Ramgarh'),
  ('Jharkhand', 'Medininagar'),
  ('Jharkhand', 'Phusro'),
  ('Jharkhand', 'Adityapur'),
  ('Jharkhand', 'Chaibasa'),
  ('Jharkhand', 'Chatra'),
  ('Jharkhand', 'Dumka'),
  ('Jharkhand', 'Garhwa'),
  ('Jharkhand', 'Godda'),
  ('Jharkhand', 'Gumla'),
  ('Jharkhand', 'Jamtara'),
  ('Jharkhand', 'Khunti'),
  ('Jharkhand', 'Koderma'),
  ('Jharkhand', 'Latehar'),
  ('Jharkhand', 'Lohardaga'),
  ('Jharkhand', 'Pakur'),
  ('Jharkhand', 'Sahibganj'),
  ('Jharkhand', 'Saraikela'),
  ('Jharkhand', 'Simdega'),
  ('Jharkhand', 'Jhumri Telaiya'),
  ('Jharkhand', 'Jasidih'),
  ('Jharkhand', 'Madhupur'),
  ('Jharkhand', 'Chirkunda'),
  ('Jharkhand', 'Chakradharpur'),
  ('Jharkhand', 'Chandil'),
  ('Jharkhand', 'Chas'),
  ('Jharkhand', 'Ghatshila'),
  ('Jharkhand', 'Gomia'),
  ('Jharkhand', 'Jugsalai'),
  ('Jharkhand', 'Mihijam'),
  ('Jharkhand', 'Nirsa'),
  ('Jharkhand', 'Patratu'),
  ('Jharkhand', 'Rajmahal'),
  ('Jharkhand', 'Sindri'),
  ('Jharkhand', 'Tenughat'),
  ('Jharkhand', 'Bermo'),
  ('Jharkhand', 'Barhi'),
  ('Jharkhand', 'Bundu'),
  ('Jharkhand', 'Hussainabad'),
  ('Jharkhand', 'Kharsawan'),
  ('Jharkhand', 'Manoharpur'),
  ('Jharkhand', 'Bagodar'),
  ('Jharkhand', 'Chandrapura'),
  ('Jharkhand', 'Dumri'),
  ('Jharkhand', 'Barkagaon'),
  ('Jharkhand', 'Domchanch'),
  ('Jharkhand', 'Nagar Untari'),
  ('Jharkhand', 'Bishrampur'),
  ('Jharkhand', 'Rajdhanwar'),
  ('Jharkhand', 'Jharia'),
  ('Jharkhand', 'Katras'),
  ('Jharkhand', 'Baharagora'),
  ('Jharkhand', 'Musabani'),
  ('Karnataka', 'Bengaluru'),
  ('Karnataka', 'Mysuru'),
  ('Karnataka', 'Hubballi'),
  ('Karnataka', 'Dharwad'),
  ('Karnataka', 'Mangaluru'),
  ('Karnataka', 'Belagavi'),
  ('Karnataka', 'Kalaburagi'),
  ('Karnataka', 'Davanagere'),
  ('Karnataka', 'Ballari'),
  ('Karnataka', 'Vijayapura'),
  ('Karnataka', 'Shivamogga'),
  ('Karnataka', 'Tumakuru'),
  ('Karnataka', 'Raichur'),
  ('Karnataka', 'Bidar'),
  ('Karnataka', 'Hassan'),
  ('Karnataka', 'Udupi'),
  ('Karnataka', 'Chitradurga'),
  ('Karnataka', 'Kolar'),
  ('Karnataka', 'Mandya'),
  ('Karnataka', 'Chikkamagaluru'),
  ('Karnataka', 'Bagalkot'),
  ('Karnataka', 'Gadag'),
  ('Karnataka', 'Haveri'),
  ('Karnataka', 'Koppal'),
  ('Karnataka', 'Yadgir'),
  ('Karnataka', 'Chikkaballapur'),
  ('Karnataka', 'Ramanagara'),
  ('Karnataka', 'Karwar'),
  ('Karnataka', 'Sirsi'),
  ('Karnataka', 'Bhadravati'),
  ('Karnataka', 'Robertsonpet'),
  ('Karnataka', 'Hospet'),
  ('Karnataka', 'Gangavathi'),
  ('Karnataka', 'Ranebennur'),
  ('Karnataka', 'Madikeri'),
  ('Karnataka', 'Hampi'),
  ('Kerala', 'Thiruvananthapuram'),
  ('Kerala', 'Kochi'),
  ('Kerala', 'Kozhikode'),
  ('Kerala', 'Thrissur'),
  ('Kerala', 'Kollam'),
  ('Kerala', 'Alappuzha'),
  ('Kerala', 'Kottayam'),
  ('Kerala', 'Palakkad'),
  ('Kerala', 'Kannur'),
  ('Kerala', 'Kasaragod'),
  ('Kerala', 'Malappuram'),
  ('Kerala', 'Pathanamthitta'),
  ('Kerala', 'Thodupuzha'),
  ('Kerala', 'Kalpetta'),
  ('Kerala', 'Guruvayur'),
  ('Kerala', 'Munnar'),
  ('Kerala', 'Varkala'),
  ('Kerala', 'Cherthala'),
  ('Kerala', 'Perinthalmanna'),
  ('Kerala', 'Tirur'),
  ('Kerala', 'Manjeri'),
  ('Kerala', 'Ponnani'),
  ('Kerala', 'Chalakudy'),
  ('Kerala', 'Aluva'),
  ('Kerala', 'Muvattupuzha'),
  ('Kerala', 'Thalassery'),
  ('Kerala', 'Payyanur'),
  ('Kerala', 'Nedumangad'),
  ('Kerala', 'Neyyattinkara'),
  ('Kerala', 'Changanassery'),
  ('Kerala', 'Thiruvalla'),
  ('Kerala', 'Kayamkulam'),
  ('Kerala', 'Kumarakom'),
  ('Ladakh', 'Leh'),
  ('Ladakh', 'Kargil'),
  ('Ladakh', 'Diskit'),
  ('Ladakh', 'Padum'),
  ('Ladakh', 'Drass'),
  ('Ladakh', 'Nubra'),
  ('Lakshadweep', 'Kavaratti'),
  ('Lakshadweep', 'Agatti'),
  ('Lakshadweep', 'Minicoy'),
  ('Lakshadweep', 'Amini'),
  ('Lakshadweep', 'Andrott'),
  ('Lakshadweep', 'Kadmat'),
  ('Lakshadweep', 'Bangaram'),
  ('Madhya Pradesh', 'Indore'),
  ('Madhya Pradesh', 'Bhopal'),
  ('Madhya Pradesh', 'Jabalpur'),
  ('Madhya Pradesh', 'Gwalior'),
  ('Madhya Pradesh', 'Ujjain'),
  ('Madhya Pradesh', 'Sagar'),
  ('Madhya Pradesh', 'Dewas'),
  ('Madhya Pradesh', 'Satna'),
  ('Madhya Pradesh', 'Ratlam'),
  ('Madhya Pradesh', 'Rewa'),
  ('Madhya Pradesh', 'Katni'),
  ('Madhya Pradesh', 'Singrauli'),
  ('Madhya Pradesh', 'Burhanpur'),
  ('Madhya Pradesh', 'Khandwa'),
  ('Madhya Pradesh', 'Morena'),
  ('Madhya Pradesh', 'Bhind'),
  ('Madhya Pradesh', 'Guna'),
  ('Madhya Pradesh', 'Shivpuri'),
  ('Madhya Pradesh', 'Vidisha'),
  ('Madhya Pradesh', 'Chhindwara'),
  ('Madhya Pradesh', 'Damoh'),
  ('Madhya Pradesh', 'Mandsaur'),
  ('Madhya Pradesh', 'Khargone'),
  ('Madhya Pradesh', 'Neemuch'),
  ('Madhya Pradesh', 'Pithampur'),
  ('Madhya Pradesh', 'Narmadapuram'),
  ('Madhya Pradesh', 'Itarsi'),
  ('Madhya Pradesh', 'Sehore'),
  ('Madhya Pradesh', 'Betul'),
  ('Madhya Pradesh', 'Seoni'),
  ('Madhya Pradesh', 'Datia'),
  ('Madhya Pradesh', 'Nagda'),
  ('Madhya Pradesh', 'Dhar'),
  ('Madhya Pradesh', 'Balaghat'),
  ('Madhya Pradesh', 'Chhatarpur'),
  ('Madhya Pradesh', 'Tikamgarh'),
  ('Madhya Pradesh', 'Shahdol'),
  ('Madhya Pradesh', 'Sidhi'),
  ('Madhya Pradesh', 'Harda'),
  ('Madhya Pradesh', 'Mhow'),
  ('Madhya Pradesh', 'Sanchi'),
  ('Madhya Pradesh', 'Maheshwar'),
  ('Madhya Pradesh', 'Omkareshwar'),
  ('Madhya Pradesh', 'Panna'),
  ('Madhya Pradesh', 'Ashoknagar'),
  ('Madhya Pradesh', 'Rajgarh'),
  ('Madhya Pradesh', 'Shajapur'),
  ('Madhya Pradesh', 'Barwani'),
  ('Madhya Pradesh', 'Jhabua'),
  ('Madhya Pradesh', 'Mandla'),
  ('Madhya Pradesh', 'Narsinghpur'),
  ('Madhya Pradesh', 'Raisen'),
  ('Madhya Pradesh', 'Khajuraho'),
  ('Maharashtra', 'Mumbai'),
  ('Maharashtra', 'Pune'),
  ('Maharashtra', 'Nagpur'),
  ('Maharashtra', 'Nashik'),
  ('Maharashtra', 'Thane'),
  ('Maharashtra', 'Chhatrapati Sambhajinagar'),
  ('Maharashtra', 'Solapur'),
  ('Maharashtra', 'Amravati'),
  ('Maharashtra', 'Kolhapur'),
  ('Maharashtra', 'Navi Mumbai'),
  ('Maharashtra', 'Kalyan'),
  ('Maharashtra', 'Dombivli'),
  ('Maharashtra', 'Vasai'),
  ('Maharashtra', 'Virar'),
  ('Maharashtra', 'Sangli'),
  ('Maharashtra', 'Jalgaon'),
  ('Maharashtra', 'Akola'),
  ('Maharashtra', 'Latur'),
  ('Maharashtra', 'Dhule'),
  ('Maharashtra', 'Ahmednagar'),
  ('Maharashtra', 'Chandrapur'),
  ('Maharashtra', 'Parbhani'),
  ('Maharashtra', 'Ichalkaranji'),
  ('Maharashtra', 'Jalna'),
  ('Maharashtra', 'Bhusawal'),
  ('Maharashtra', 'Panvel'),
  ('Maharashtra', 'Satara'),
  ('Maharashtra', 'Beed'),
  ('Maharashtra', 'Yavatmal'),
  ('Maharashtra', 'Dharashiv'),
  ('Maharashtra', 'Nanded'),
  ('Maharashtra', 'Wardha'),
  ('Maharashtra', 'Udgir'),
  ('Maharashtra', 'Hingoli'),
  ('Maharashtra', 'Ratnagiri'),
  ('Maharashtra', 'Sindhudurg'),
  ('Maharashtra', 'Alibaug'),
  ('Maharashtra', 'Lonavala'),
  ('Maharashtra', 'Mahabaleshwar'),
  ('Maharashtra', 'Shirdi'),
  ('Maharashtra', 'Karad'),
  ('Maharashtra', 'Baramati'),
  ('Maharashtra', 'Pandharpur'),
  ('Maharashtra', 'Malegaon'),
  ('Maharashtra', 'Gondia'),
  ('Maharashtra', 'Bhandara'),
  ('Maharashtra', 'Washim'),
  ('Maharashtra', 'Buldhana'),
  ('Maharashtra', 'Nandurbar'),
  ('Maharashtra', 'Palghar'),
  ('Maharashtra', 'Khopoli'),
  ('Maharashtra', 'Igatpuri'),
  ('Maharashtra', 'Wai'),
  ('Manipur', 'Imphal'),
  ('Manipur', 'Thoubal'),
  ('Manipur', 'Bishnupur'),
  ('Manipur', 'Churachandpur'),
  ('Manipur', 'Kakching'),
  ('Manipur', 'Ukhrul'),
  ('Manipur', 'Senapati'),
  ('Manipur', 'Tamenglong'),
  ('Manipur', 'Jiribam'),
  ('Manipur', 'Moreh'),
  ('Manipur', 'Chandel'),
  ('Manipur', 'Kangpokpi'),
  ('Manipur', 'Noney'),
  ('Manipur', 'Tengnoupal'),
  ('Meghalaya', 'Shillong'),
  ('Meghalaya', 'Tura'),
  ('Meghalaya', 'Jowai'),
  ('Meghalaya', 'Nongstoin'),
  ('Meghalaya', 'Baghmara'),
  ('Meghalaya', 'Williamnagar'),
  ('Meghalaya', 'Nongpoh'),
  ('Meghalaya', 'Resubelpara'),
  ('Meghalaya', 'Ampati'),
  ('Meghalaya', 'Mairang'),
  ('Meghalaya', 'Khliehriat'),
  ('Meghalaya', 'Sohra'),
  ('Meghalaya', 'Mawsynram'),
  ('Meghalaya', 'Dawki'),
  ('Mizoram', 'Aizawl'),
  ('Mizoram', 'Lunglei'),
  ('Mizoram', 'Champhai'),
  ('Mizoram', 'Serchhip'),
  ('Mizoram', 'Kolasib'),
  ('Mizoram', 'Saiha'),
  ('Mizoram', 'Lawngtlai'),
  ('Mizoram', 'Mamit'),
  ('Mizoram', 'Khawzawl'),
  ('Mizoram', 'Hnahthial'),
  ('Mizoram', 'Saitual'),
  ('Nagaland', 'Kohima'),
  ('Nagaland', 'Dimapur'),
  ('Nagaland', 'Mokokchung'),
  ('Nagaland', 'Tuensang'),
  ('Nagaland', 'Wokha'),
  ('Nagaland', 'Zunheboto'),
  ('Nagaland', 'Mon'),
  ('Nagaland', 'Phek'),
  ('Nagaland', 'Kiphire'),
  ('Nagaland', 'Longleng'),
  ('Nagaland', 'Peren'),
  ('Nagaland', 'Chumukedima'),
  ('Nagaland', 'Noklak'),
  ('Odisha', 'Bhubaneswar'),
  ('Odisha', 'Cuttack'),
  ('Odisha', 'Rourkela'),
  ('Odisha', 'Brahmapur'),
  ('Odisha', 'Sambalpur'),
  ('Odisha', 'Puri'),
  ('Odisha', 'Balasore'),
  ('Odisha', 'Bhadrak'),
  ('Odisha', 'Baripada'),
  ('Odisha', 'Jharsuguda'),
  ('Odisha', 'Jeypore'),
  ('Odisha', 'Bargarh'),
  ('Odisha', 'Rayagada'),
  ('Odisha', 'Bhawanipatna'),
  ('Odisha', 'Angul'),
  ('Odisha', 'Dhenkanal'),
  ('Odisha', 'Paradip'),
  ('Odisha', 'Kendrapara'),
  ('Odisha', 'Jajpur'),
  ('Odisha', 'Talcher'),
  ('Odisha', 'Sundargarh'),
  ('Odisha', 'Koraput'),
  ('Odisha', 'Nabarangpur'),
  ('Odisha', 'Nuapada'),
  ('Odisha', 'Boudh'),
  ('Odisha', 'Sonepur'),
  ('Odisha', 'Phulbani'),
  ('Odisha', 'Malkangiri'),
  ('Odisha', 'Deogarh'),
  ('Odisha', 'Khordha'),
  ('Odisha', 'Nayagarh'),
  ('Odisha', 'Keonjhar'),
  ('Odisha', 'Konark'),
  ('Puducherry', 'Puducherry'),
  ('Puducherry', 'Karaikal'),
  ('Puducherry', 'Yanam'),
  ('Puducherry', 'Mahe'),
  ('Puducherry', 'Villianur'),
  ('Puducherry', 'Ozhukarai'),
  ('Puducherry', 'Auroville'),
  ('Punjab', 'Ludhiana'),
  ('Punjab', 'Amritsar'),
  ('Punjab', 'Jalandhar'),
  ('Punjab', 'Patiala'),
  ('Punjab', 'Bathinda'),
  ('Punjab', 'Mohali'),
  ('Punjab', 'Hoshiarpur'),
  ('Punjab', 'Batala'),
  ('Punjab', 'Pathankot'),
  ('Punjab', 'Moga'),
  ('Punjab', 'Abohar'),
  ('Punjab', 'Malerkotla'),
  ('Punjab', 'Khanna'),
  ('Punjab', 'Phagwara'),
  ('Punjab', 'Muktsar'),
  ('Punjab', 'Barnala'),
  ('Punjab', 'Rajpura'),
  ('Punjab', 'Firozpur'),
  ('Punjab', 'Kapurthala'),
  ('Punjab', 'Sangrur'),
  ('Punjab', 'Faridkot'),
  ('Punjab', 'Gurdaspur'),
  ('Punjab', 'Zirakpur'),
  ('Punjab', 'Nabha'),
  ('Punjab', 'Mansa'),
  ('Punjab', 'Nawanshahr'),
  ('Punjab', 'Fazilka'),
  ('Punjab', 'Sunam'),
  ('Punjab', 'Tarn Taran'),
  ('Punjab', 'Rupnagar'),
  ('Punjab', 'Anandpur Sahib'),
  ('Punjab', 'Fatehgarh Sahib'),
  ('Punjab', 'Kharar'),
  ('Punjab', 'Dera Bassi'),
  ('Punjab', 'Jagraon'),
  ('Punjab', 'Samana'),
  ('Rajasthan', 'Jaipur'),
  ('Rajasthan', 'Jodhpur'),
  ('Rajasthan', 'Udaipur'),
  ('Rajasthan', 'Kota'),
  ('Rajasthan', 'Bikaner'),
  ('Rajasthan', 'Ajmer'),
  ('Rajasthan', 'Bhilwara'),
  ('Rajasthan', 'Alwar'),
  ('Rajasthan', 'Sikar'),
  ('Rajasthan', 'Pali'),
  ('Rajasthan', 'Sri Ganganagar'),
  ('Rajasthan', 'Bharatpur'),
  ('Rajasthan', 'Hanumangarh'),
  ('Rajasthan', 'Jhunjhunu'),
  ('Rajasthan', 'Churu'),
  ('Rajasthan', 'Nagaur'),
  ('Rajasthan', 'Barmer'),
  ('Rajasthan', 'Tonk'),
  ('Rajasthan', 'Chittorgarh'),
  ('Rajasthan', 'Banswara'),
  ('Rajasthan', 'Dausa'),
  ('Rajasthan', 'Baran'),
  ('Rajasthan', 'Bundi'),
  ('Rajasthan', 'Jaisalmer'),
  ('Rajasthan', 'Sawai Madhopur'),
  ('Rajasthan', 'Dungarpur'),
  ('Rajasthan', 'Rajsamand'),
  ('Rajasthan', 'Jhalawar'),
  ('Rajasthan', 'Karauli'),
  ('Rajasthan', 'Pratapgarh'),
  ('Rajasthan', 'Sirohi'),
  ('Rajasthan', 'Mount Abu'),
  ('Rajasthan', 'Beawar'),
  ('Rajasthan', 'Kishangarh'),
  ('Rajasthan', 'Makrana'),
  ('Rajasthan', 'Fatehpur'),
  ('Rajasthan', 'Nathdwara'),
  ('Rajasthan', 'Pushkar'),
  ('Rajasthan', 'Neemrana'),
  ('Rajasthan', 'Bhiwadi'),
  ('Rajasthan', 'Abu Road'),
  ('Rajasthan', 'Sujangarh'),
  ('Rajasthan', 'Balotra'),
  ('Rajasthan', 'Phalodi'),
  ('Sikkim', 'Gangtok'),
  ('Sikkim', 'Namchi'),
  ('Sikkim', 'Gyalshing'),
  ('Sikkim', 'Mangan'),
  ('Sikkim', 'Rangpo'),
  ('Sikkim', 'Singtam'),
  ('Sikkim', 'Jorethang'),
  ('Sikkim', 'Ravangla'),
  ('Sikkim', 'Pelling'),
  ('Sikkim', 'Lachung'),
  ('Sikkim', 'Soreng'),
  ('Sikkim', 'Pakyong'),
  ('Tamil Nadu', 'Chennai'),
  ('Tamil Nadu', 'Coimbatore'),
  ('Tamil Nadu', 'Madurai'),
  ('Tamil Nadu', 'Tiruchirappalli'),
  ('Tamil Nadu', 'Salem'),
  ('Tamil Nadu', 'Tirunelveli'),
  ('Tamil Nadu', 'Tiruppur'),
  ('Tamil Nadu', 'Erode'),
  ('Tamil Nadu', 'Vellore'),
  ('Tamil Nadu', 'Thoothukudi'),
  ('Tamil Nadu', 'Dindigul'),
  ('Tamil Nadu', 'Thanjavur'),
  ('Tamil Nadu', 'Ranipet'),
  ('Tamil Nadu', 'Sivakasi'),
  ('Tamil Nadu', 'Karur'),
  ('Tamil Nadu', 'Udhagamandalam'),
  ('Tamil Nadu', 'Hosur'),
  ('Tamil Nadu', 'Nagercoil'),
  ('Tamil Nadu', 'Kanchipuram'),
  ('Tamil Nadu', 'Kumbakonam'),
  ('Tamil Nadu', 'Cuddalore'),
  ('Tamil Nadu', 'Karaikudi'),
  ('Tamil Nadu', 'Neyveli'),
  ('Tamil Nadu', 'Tiruvannamalai'),
  ('Tamil Nadu', 'Pollachi'),
  ('Tamil Nadu', 'Rajapalayam'),
  ('Tamil Nadu', 'Pudukkottai'),
  ('Tamil Nadu', 'Ambur'),
  ('Tamil Nadu', 'Nagapattinam'),
  ('Tamil Nadu', 'Virudhunagar'),
  ('Tamil Nadu', 'Mayiladuthurai'),
  ('Tamil Nadu', 'Krishnagiri'),
  ('Tamil Nadu', 'Namakkal'),
  ('Tamil Nadu', 'Perambalur'),
  ('Tamil Nadu', 'Ariyalur'),
  ('Tamil Nadu', 'Villupuram'),
  ('Tamil Nadu', 'Tenkasi'),
  ('Tamil Nadu', 'Theni'),
  ('Tamil Nadu', 'Ramanathapuram'),
  ('Tamil Nadu', 'Sivaganga'),
  ('Tamil Nadu', 'Dharmapuri'),
  ('Tamil Nadu', 'Tirupathur'),
  ('Tamil Nadu', 'Kallakurichi'),
  ('Tamil Nadu', 'Chengalpattu'),
  ('Tamil Nadu', 'Tambaram'),
  ('Tamil Nadu', 'Avadi'),
  ('Tamil Nadu', 'Mahabalipuram'),
  ('Tamil Nadu', 'Yercaud'),
  ('Tamil Nadu', 'Kodaikanal'),
  ('Tamil Nadu', 'Rameswaram'),
  ('Telangana', 'Hyderabad'),
  ('Telangana', 'Secunderabad'),
  ('Telangana', 'Warangal'),
  ('Telangana', 'Nizamabad'),
  ('Telangana', 'Karimnagar'),
  ('Telangana', 'Khammam'),
  ('Telangana', 'Ramagundam'),
  ('Telangana', 'Mahbubnagar'),
  ('Telangana', 'Nalgonda'),
  ('Telangana', 'Adilabad'),
  ('Telangana', 'Suryapet'),
  ('Telangana', 'Miryalaguda'),
  ('Telangana', 'Jagtial'),
  ('Telangana', 'Mancherial'),
  ('Telangana', 'Siddipet'),
  ('Telangana', 'Kothagudem'),
  ('Telangana', 'Bhongir'),
  ('Telangana', 'Sangareddy'),
  ('Telangana', 'Medak'),
  ('Telangana', 'Vikarabad'),
  ('Telangana', 'Wanaparthy'),
  ('Telangana', 'Nagarkurnool'),
  ('Telangana', 'Gadwal'),
  ('Telangana', 'Kamareddy'),
  ('Telangana', 'Peddapalli'),
  ('Telangana', 'Jangaon'),
  ('Telangana', 'Bhadrachalam'),
  ('Telangana', 'Nirmal'),
  ('Telangana', 'Mulugu'),
  ('Telangana', 'Narayanpet'),
  ('Telangana', 'Sircilla'),
  ('Telangana', 'Medchal'),
  ('Telangana', 'Shamshabad'),
  ('Tripura', 'Agartala'),
  ('Tripura', 'Udaipur'),
  ('Tripura', 'Dharmanagar'),
  ('Tripura', 'Kailashahar'),
  ('Tripura', 'Belonia'),
  ('Tripura', 'Ambassa'),
  ('Tripura', 'Khowai'),
  ('Tripura', 'Sabroom'),
  ('Tripura', 'Sonamura'),
  ('Tripura', 'Teliamura'),
  ('Tripura', 'Melaghar'),
  ('Tripura', 'Kamalpur'),
  ('Tripura', 'Bishalgarh'),
  ('Uttar Pradesh', 'Lucknow'),
  ('Uttar Pradesh', 'Kanpur'),
  ('Uttar Pradesh', 'Ghaziabad'),
  ('Uttar Pradesh', 'Agra'),
  ('Uttar Pradesh', 'Varanasi'),
  ('Uttar Pradesh', 'Meerut'),
  ('Uttar Pradesh', 'Prayagraj'),
  ('Uttar Pradesh', 'Bareilly'),
  ('Uttar Pradesh', 'Aligarh'),
  ('Uttar Pradesh', 'Moradabad'),
  ('Uttar Pradesh', 'Saharanpur'),
  ('Uttar Pradesh', 'Gorakhpur'),
  ('Uttar Pradesh', 'Noida'),
  ('Uttar Pradesh', 'Greater Noida'),
  ('Uttar Pradesh', 'Firozabad'),
  ('Uttar Pradesh', 'Jhansi'),
  ('Uttar Pradesh', 'Muzaffarnagar'),
  ('Uttar Pradesh', 'Mathura'),
  ('Uttar Pradesh', 'Vrindavan'),
  ('Uttar Pradesh', 'Rampur'),
  ('Uttar Pradesh', 'Shahjahanpur'),
  ('Uttar Pradesh', 'Farrukhabad'),
  ('Uttar Pradesh', 'Ayodhya'),
  ('Uttar Pradesh', 'Faizabad'),
  ('Uttar Pradesh', 'Hapur'),
  ('Uttar Pradesh', 'Etawah'),
  ('Uttar Pradesh', 'Mirzapur'),
  ('Uttar Pradesh', 'Bulandshahr'),
  ('Uttar Pradesh', 'Sambhal'),
  ('Uttar Pradesh', 'Amroha'),
  ('Uttar Pradesh', 'Hardoi'),
  ('Uttar Pradesh', 'Fatehpur'),
  ('Uttar Pradesh', 'Raebareli'),
  ('Uttar Pradesh', 'Orai'),
  ('Uttar Pradesh', 'Sitapur'),
  ('Uttar Pradesh', 'Bahraich'),
  ('Uttar Pradesh', 'Unnao'),
  ('Uttar Pradesh', 'Jaunpur'),
  ('Uttar Pradesh', 'Lakhimpur'),
  ('Uttar Pradesh', 'Hathras'),
  ('Uttar Pradesh', 'Banda'),
  ('Uttar Pradesh', 'Pilibhit'),
  ('Uttar Pradesh', 'Barabanki'),
  ('Uttar Pradesh', 'Gonda'),
  ('Uttar Pradesh', 'Mainpuri'),
  ('Uttar Pradesh', 'Lalitpur'),
  ('Uttar Pradesh', 'Etah'),
  ('Uttar Pradesh', 'Deoria'),
  ('Uttar Pradesh', 'Ghazipur'),
  ('Uttar Pradesh', 'Sultanpur'),
  ('Uttar Pradesh', 'Azamgarh'),
  ('Uttar Pradesh', 'Bijnor'),
  ('Uttar Pradesh', 'Basti'),
  ('Uttar Pradesh', 'Ballia'),
  ('Uttar Pradesh', 'Mau'),
  ('Uttar Pradesh', 'Kannauj'),
  ('Uttar Pradesh', 'Kasganj'),
  ('Uttar Pradesh', 'Kushinagar'),
  ('Uttar Pradesh', 'Maharajganj'),
  ('Uttar Pradesh', 'Bhadohi'),
  ('Uttar Pradesh', 'Sonbhadra'),
  ('Uttar Pradesh', 'Chandauli'),
  ('Uttar Pradesh', 'Amethi'),
  ('Uttar Pradesh', 'Balrampur'),
  ('Uttar Pradesh', 'Loni'),
  ('Uttar Pradesh', 'Baghpat'),
  ('Uttar Pradesh', 'Chitrakoot'),
  ('Uttar Pradesh', 'Sarnath'),
  ('Uttarakhand', 'Dehradun'),
  ('Uttarakhand', 'Haridwar'),
  ('Uttarakhand', 'Rishikesh'),
  ('Uttarakhand', 'Roorkee'),
  ('Uttarakhand', 'Haldwani'),
  ('Uttarakhand', 'Kashipur'),
  ('Uttarakhand', 'Rudrapur'),
  ('Uttarakhand', 'Nainital'),
  ('Uttarakhand', 'Mussoorie'),
  ('Uttarakhand', 'Almora'),
  ('Uttarakhand', 'Pithoragarh'),
  ('Uttarakhand', 'Kotdwar'),
  ('Uttarakhand', 'Ramnagar'),
  ('Uttarakhand', 'Pauri'),
  ('Uttarakhand', 'Srinagar Garhwal'),
  ('Uttarakhand', 'New Tehri'),
  ('Uttarakhand', 'Bageshwar'),
  ('Uttarakhand', 'Champawat'),
  ('Uttarakhand', 'Gopeshwar'),
  ('Uttarakhand', 'Uttarkashi'),
  ('Uttarakhand', 'Rudraprayag'),
  ('Uttarakhand', 'Jaspur'),
  ('Uttarakhand', 'Manglaur'),
  ('Uttarakhand', 'Sitarganj'),
  ('Uttarakhand', 'Khatima'),
  ('Uttarakhand', 'Vikasnagar'),
  ('Uttarakhand', 'Doiwala'),
  ('Uttarakhand', 'Auli'),
  ('Uttarakhand', 'Badrinath'),
  ('Uttarakhand', 'Kedarnath'),
  ('West Bengal', 'Kolkata'),
  ('West Bengal', 'Howrah'),
  ('West Bengal', 'Durgapur'),
  ('West Bengal', 'Asansol'),
  ('West Bengal', 'Siliguri'),
  ('West Bengal', 'Bardhaman'),
  ('West Bengal', 'Malda'),
  ('West Bengal', 'Baharampur'),
  ('West Bengal', 'Habra'),
  ('West Bengal', 'Kharagpur'),
  ('West Bengal', 'Shantipur'),
  ('West Bengal', 'Dankuni'),
  ('West Bengal', 'Darjeeling'),
  ('West Bengal', 'Kalimpong'),
  ('West Bengal', 'Jalpaiguri'),
  ('West Bengal', 'Cooch Behar'),
  ('West Bengal', 'Alipurduar'),
  ('West Bengal', 'Raiganj'),
  ('West Bengal', 'Balurghat'),
  ('West Bengal', 'Krishnanagar'),
  ('West Bengal', 'Barasat'),
  ('West Bengal', 'Bidhannagar'),
  ('West Bengal', 'Serampore'),
  ('West Bengal', 'Chandannagar'),
  ('West Bengal', 'Hooghly'),
  ('West Bengal', 'Bankura'),
  ('West Bengal', 'Purulia'),
  ('West Bengal', 'Midnapore'),
  ('West Bengal', 'Haldia'),
  ('West Bengal', 'Tamluk'),
  ('West Bengal', 'Diamond Harbour'),
  ('West Bengal', 'Basirhat'),
  ('West Bengal', 'Bongaon'),
  ('West Bengal', 'Nabadwip'),
  ('West Bengal', 'Katwa'),
  ('West Bengal', 'Kalna'),
  ('West Bengal', 'Arambagh'),
  ('West Bengal', 'Suri'),
  ('West Bengal', 'Bolpur'),
  ('West Bengal', 'Rampurhat'),
  ('West Bengal', 'Jhargram'),
  ('West Bengal', 'Digha'),
  ('West Bengal', 'Barrackpore'),
  ('West Bengal', 'Naihati'),
  ('West Bengal', 'Kanchrapara'),
  ('West Bengal', 'Bhatpara'),
  ('West Bengal', 'Titagarh'),
  ('West Bengal', 'Uttarpara')
) as v(state, city)
where not exists (
  select 1 from public.locations l where lower(l.city) = lower(v.city)
);
